version: "3.3"
services:
  postgres:
     image: 'postgres:latest'
     command: postgres -c 'max_connections=500'
     restart: always
     environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
          - PUID=1000
          - PGID=1000
     logging:
          options:
               max-size: 10m
               max-file: "3"
     ports:
          - '5432:5432'
     volumes:
          - pg_bookings:/var/lib/postgresql/data
volumes:
  pg_bookings:
    external: true
